[package]
name = "echo-jsonrpc"
version = "0.1.0"
authors = ["Michal 'vorner' Vaner <vorner@vorner.cz>"]

[dependencies]
futures = "0.1"
tokio-core = "0.1"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"

[profile.dev]
codegen-units = 4

[profile.test]
codegen-units = 4
